#!/bin/bash -l
#SBATCH -J Ag2_OPT
#SBATCH -q debug
#SBATCH -N 8
#SBATCH -C haswell
#SBATCH -t 00:30:00
#SBATCH -o so_qwalk.o%j

HOME=`pwd`


#srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ag2.hf

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ag2.opt 

sed 's/OPTIMIZEBASIS//g' Ag2.opt.wfout > fixed_basis.wfout

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ag2.linear
