#!/bin/bash -l
#SBATCH -J Pt_AE_4
#SBATCH -q regular
#!SBATCH -q debug
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 04:00:00
#SBATCH -o Pt_DKH.o%j

module load molpro

molpro -n 12 3.com
