#!/bin/bash -l
#SBATCH -J AgH_uc
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 2:00:00
#SBATCH -o mol_molpro.o%j

module load molpro
molpro -n 4 tz.com
molpro -n 4 qz.com
molpro -n 4 5z.com
