#!/bin/bash -l
#SBATCH -J Bi2_job
#SBATCH -q regular
#SBATCH -N 8
#SBATCH -C knl
#SBATCH -t 1:30:00
#SBATCH -o so_qwalk.o%j

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi2.df > DF.log

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi2.opt > OPT.log

sed 's/OPTIMIZEBASIS//g' Bi2.opt.wfout > fixed_basis.wfout

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi2.linear > LINEAR.log

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi2.dmc > DMC.log
