#!/bin/bash -l
#SBATCH -J Ag2_DMC_PBE
#SBATCH -q low
#SBATCH -N 8
#!SBATCH -n 16
#SBATCH -C knl
#SBATCH -t 1:30:00
#!SBATCH --time-min=00:45:00
#SBATCH -o mol_molpro.o%j


HOME=`pwd`

#srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Ag2.df

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Ag2.opt 

sed 's/OPTIMIZEBASIS//g' Ag2.opt.wfout > fixed_basis.wfout

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Ag2.linear

