#!/usr/bin/env bash

HOME=`pwd`

declare -a basis=("cc-pVDZ" "aug-cc-pVDZ" "aug-cc-pVTZ" "cc-pVQZ" "aug-cc-pVQZ" "cc-pV5Z" "aug-cc-pV5Z")

for i in "${basis[@]}"

do
	echo ${i}
	cd $HOME/old_basis
	cp cc-pVTZ.com ${i}.com
	cp cc-pVTZ.slurm ${i}.slurm
	sed -i "s/cc-pVTZ/${i}/" ${i}.com
	sed -i "s/cc-pVTZ/${i}/" ${i}.slurm
	sbatch ${i}.slurm
done


