#!/bin/bash
#COBALT -t 03:00:00
#COBALT -n 128
#COBALT -A PSFMat_2               
#COBALT -o myqwalk.o%j         
#COBALT -q default
#COBALT --attrs mcdram=cache:numa=quad

HOME=`pwd`




aprun -n 8192 -N 64 qwalk-so Ag.df
aprun -n 8192 -N 64 qwalk-so Ag.opt 

sed 's/OPTIMIZEBASIS//g' Ag.opt.wfout > fixed_basis.wfout

aprun -n 8192 -N 64 qwalk-so Ag.linear

aprun -n 8192 -N 64 qwalk-so Ag.dmc



