#!/bin/bash -l
#SBATCH -J AgO_ae
#SBATCH -q premium
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 48:00:00
#SBATCH -o mol_molpro.o%j

module load molpro
molpro -n 24 dz.com
molpro -n 24 tz.com
molpro -n 24 qz.com
