#!/bin/bash
#COBALT -t 02:50:00
#COBALT -n 128
#COBALT -A PSFMat_2               
#COBALT -o myqwalk.o%j         
#COBALT -q default
#COBALT --attrs mcdram=cache:numa=quad

HOME=/projects/PSFMat_2/gwang18/projects/so-ccecp/bi-soc/soc/dmc/atom/mdfstu/


cd $HOME/gs/state1/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/gs/state2/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/gs/state3/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/gs/state4/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/gs/state5/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ea/state1/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip1/state1/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip1/state2/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip1/state3/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip1/state4/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip1/state5/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip2/state1/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip2/state2/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip2-d/state1/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip2-d/state2/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip2-f/state1/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

cd $HOME/ip2-f/state2/
aprun -n 8192 -N 64 qwalk-so Bi.dmc

