#!/bin/bash -l
#SBATCH -J test_molpro
#SBATCH -q regular
#!SBATCH -q debug
#SBATCH -N 1
#!SBATCH -n 16
#!SBATCH -C haswell
#SBATCH -C knl
#SBATCH -t 02:20:00
#SBATCH -o test_molpro.o%j

module load molpro

molpro -n 24 tz.com
