#!/bin/bash


#mark current directory
HOME=pwd
toev=27.21138
ref=`awk 'NR==1{print $1}' energy.dat`
awk -v ref=$ref '{printf("%.3f\n", 27.21138*($1-ref))}' energy.dat > energy.gaps
#awk '{printf("%.2f\n", $1-$2)}' workdir/spect > workdir/spectra
#cat workdir/spectra

