#!/bin/bash -l
#SBATCH -J W2_OPT
#SBATCH -q regular
#SBATCH -N 8
#SBATCH -C haswell
#SBATCH -t 00:45:00
#SBATCH -o so_qwalk.o%j

HOME=`pwd`


srun -n 512 -c 1 --cpu_bind=threads qwalk-so W2.opt 

sed 's/OPTIMIZEBASIS//g' W2.opt.wfout > fixed_basis.wfout

srun -n 512 -c 1 --cpu_bind=threads qwalk-so W2.linear 

sbatch $HOME/jobdmc
