#!/bin/bash -l
#SBATCH -J SrO_ae
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 20:00:00
#SBATCH -o mol_molpro.o%j

module load molpro
#molpro -n 4 dz.com
#molpro -n 4 tz.com
molpro -n 8 qz.com
