#!/usr/bin/bash

HOME=`pwd`
INP='/home/haihan/Research/HZECP/mo-so/mo0/ppinput'
MOL='/home/haihan/Research/HZECP/mo-so/mo-cosci/ccECP/gs/dirac'
STATE='/home/haihan/Research/HZECP/mo-so/mo-cosci/ccECP/gs/state1'

mkdir $HOME/dirac
mkdir $HOME/state1
cp $INP/4p.inp $HOME/dirac/
cp $MOL/core.inp $HOME/dirac/
cp $MOL/pp.mol $HOME/dirac/
cp $MOL/ecp_class.py $HOME/dirac
cp $MOL/orbconv.py $HOME/dirac
cp $MOL/slater.py $HOME/dirac
cp $MOL/code.use $HOME/dirac

for i in 1 2
do
cp -r $STATE $HOME/state$i
done
