#!/bin/bash -l
#SBATCH -J test_molpro
#SBATCH -q premium
#!SBATCH -N 1
#SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 08:30:00
#SBATCH -o test_molpro.o%j

module load molpro
#molpro -n 24 dz.com
#molpro -n 24 tz.com
#molpro -n 24 qz.com
molpro -n 24 5z.com
