#!/bin/bash -l
#SBATCH -J Pt_CREN
#!SBATCH -q regular
#SBATCH -q debug
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 00:30:00
#SBATCH -o test_molpro.o%j

module load molpro

molpro -n 12 3.com
