#!/bin/bash


#mark current directory
HOME=pwd
toev=27.21138
ref=`awk 'NR==1{print $1}' ex.dat`
awk -v ref=$ref '{printf("%.8f\n", ($1-ref))}' ex.dat > ex.gaps
#awk '{printf("%.2f\n", $1-$2)}' workdir/spect > workdir/spectra
#cat workdir/spectra

