#!/bin/bash -l
#SBATCH -J PtO-2.0
#SBATCH -q regular
#!SBATCH -q debug
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 6:00:00
#SBATCH -o test_molpro.o%j

module load molpro

molpro -n 12 3.com
