#!/bin/bash -l
#SBATCH -J I_job
#SBATCH -q regular
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -t 00:25:00
#SBATCH -o so_qwalk.o%j

#srun -n 64 -c 1 --cpu_bind=threads qwalk-so I.df > DF.log

srun -n 64 -c 1 --cpu_bind=threads qwalk-so I.opt > OPT.log

sed 's/OPTIMIZEBASIS//g' I.opt.wfout > fixed_basis.wfout

srun -n 64 -c 1 --cpu_bind=threads qwalk-so I.linear > LINEAR.log

#srun -n 512 -c 1 --cpu_bind=threads qwalk-so I.dmc > DMC.log
