#!/bin/bash -l
#SBATCH -J atom
##SBATCH -q debug
##SBATCH -q premium
#SBATCH -q regular
#SBATCH -N 1
##SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 05:00:00
#SBATCH -o run.o%j

module load molpro

molpro -n 10 run.com
