#!/bin/bash
pwd=`pwd`
#echo $pwd
rm table.dat
for d in */ ; do
	cd $d
	bash analyze.sh
	echo "$d" >> ../table.dat
	cat result.out >> ../table.dat
	#echo "" >> ../table.dat

	cd ../
done
cat table.dat
