#!/bin/bash -l
#SBATCH -J test_molpro
#!SBATCH -q debug
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 15:20:00
#SBATCH -o test_molpro.o%j

module load molpro

molpro -n 16 qz.com
