#!/bin/bash -l
#SBATCH -J Bi_DMC_OPT
#SBATCH -q low
#SBATCH -N 8
#!SBATCH -n 16
#SBATCH -C knl
#SBATCH -t 00:12:00
#!SBATCH --time-min=00:05:00
#SBATCH -o mol_molpro.o%j


HOME=`pwd`

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi.df

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi.opt 

sed 's/OPTIMIZEBASIS//g' Bi.opt.wfout > fixed_basis.wfout

srun -n 2176 -c 1 --cpu_bind=threads qwalk-so Bi.linear 
