#!/bin/bash
HOME=`pwd`

declare -a states=("gs" "ex" "ea" "ip1" "ip2" "p1" "4p")
declare -a mult_num=(7 5 1 5 5 2 2)

num_states=${#states[@]}

for (( i=0; i<$num_states; i++))
do
	state=${states[$i]}
	num=${mult_num[$i]}

	for ((j=1; j<=$num; j++))
	do
		cp $HOME/../templates/* $HOME/../$state/state$j
	done
done

for (( i=0; i<$num_states; i++))
do
        state=${states[$i]}
        num=${mult_num[$i]}

        for ((j=1; j<=$num; j++))
        do
                cp $HOME/../$state/dirac/new.orb $HOME/../$state/state$j/Mo.orb
        done

	cp $HOME/../$state/dirac/new.orb $HOME/../$state/opt/Mo.orb
	cp $HOME/../$state/state1/Mo.slater $HOME/../$state/opt/Mo.slater
done

