proc Id5s1
{rhf
 start,atden
 print,orbitals=2
 wf,14,1,6
 occ,4,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2,1
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,4,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 wf,14,1,6; state,1
 restrict,1,1,4.1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,14,1,6
 occ,4,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
}
endproc



proc Id5
{rhf
 start,atden
 print,orbitals=2
 wf,13,1,5
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,13,1,5
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
}
endproc




proc Id5p1
{rhf
 start,atden
 print,orbitals=2
 wf,14,2,6
 occ,3,2,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,3,2,2,1,2,1,1
 closed,1,1,1,0,1,0,0
 wf,14,2,6;state,1
 restrict,1,1,2.2
 wf,14,3,6;state,1
 restrict,1,1,2.3
 wf,14,5,6;state,1
 restrict,1,1,2.5
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,14,2,6
 occ,3,2,1,1,1,1,1
 closed,1,1,1,0,1,0,0
}
endproc




proc EAd5s2
{rhf
 start,atden
 print,orbitals=2
 wf,15,1,5
 occ,4,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 sym,1,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,4,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,15,1,5
 occ,4,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,1,3,2
}
endproc




proc IId4s1
{rhf
 start,atden
 print,orbitals=2
 wf,13,1,5
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,4,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 wf,13,1,5;state,2
 restrict,1,1,2.1
 wf,13,4,5;state,1
 restrict,1,1,2.1
 wf,13,6,5;state,1
 restrict,1,1,2.1
 wf,13,7,5;state,1
 restrict,1,1,2.1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,13,1,5
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,1,3,2
}
endproc






proc IId4s2
{rhf
 start,atden
 print,orbitals=2
 wf,14,1,4
 occ,3,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 sym,1,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,4,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 wf,14,1,4;state,2
 wf,14,4,4;state,1
 wf,14,6,4;state,1
 wf,14,7,4;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,14,1,4
 occ,3,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 sym,1,1,1,3,2
}
endproc



proc IId3s2
{rhf
 start,atden
 print,orbitals=2
 wf,13,1,3
 occ,2,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 sym,1,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,4,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 wf,13,1,3;state,1
 wf,13,4,3;state,3
 wf,13,6,3;state,3
 wf,13,7,3;state,3
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,13,1,3
 occ,2,1,1,1,1,1,1
 closed,2,1,1,0,1,0,0
 sym,1,1,1,3,2
}
endproc





proc IIId4
{rhf
 start,atden
 print,orbitals=2
 wf,12,1,4
 occ,2,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 wf,12,1,4;state,2
 wf,12,4,4;state,1
 wf,12,6,4;state,1
 wf,12,7,4;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,12,1,4
 occ,2,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
}
endproc




proc IVd3
{rhf
 start,atden
 print,orbitals=2
 wf,11,1,3
 occ,1,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 wf,11,1,3;state,1
 wf,11,4,3;state,3
 wf,11,6,3;state,3
 wf,11,7,3;state,3
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,11,1,3
 occ,1,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
}
endproc




proc Vd2
{rhf
 start,atden
 print,orbitals=2
 wf,10,1,2
 occ,3,1,1,0,1,0,0
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 wf,10,1,2;state,1
 wf,10,4,2;state,3
 wf,10,6,2;state,3
 wf,10,7,2;state,3
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,10,1,2
 occ,3,1,1,0,1,0,0
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
}
endproc





proc VId1
{rhf
 start,atden
 print,orbitals=2
 wf,9,1,1
 occ,2,1,1,0,1,0,0
 closed,1,1,1,0,1,0,0
 sym,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,3,1,1,1,1,1,1
 closed,1,1,1,0,1,0,0
 wf,9,1,1;state,2
 wf,9,4,1;state,1
 wf,9,6,1;state,1
 wf,9,7,1;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,9,1,1
 occ,2,1,1,0,1,0,0
 closed,1,1,1,0,1,0,0
}
endproc





proc VIp1
{rhf
 start,atden
 print,orbitals=2
 wf,9,2,1
 occ,1,2,1,0,1,0,0
 closed,1,1,1,0,1,0,0
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,1,2,2,0,2,0,0
 closed,1,1,1,0,1,0,0
 wf,9,2,1;state,1
 restrict,1,1,2.2
 wf,9,3,1;state,1
 restrict,1,1,2.3
 wf,9,5,1;state,1
 restrict,1,1,2.5
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,9,2,1
 occ,1,2,1,0,1,0,0
 closed,1,1,1,0,1,0,0
}
endproc




proc VI5f1
{rhf
 start,atden
 print,orbitals=2
 wf,9,2,1
 occ,1,2,1,0,1,0,0
 closed,1,1,1,0,1,0,0
 sym,2,1,3,2
 sym,3,1,3,2
 sym,5,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,1,3,3,0,3,0,0,1
 closed,1,1,1,0,1,0,0
 wf,9,2,1;state,2
 wf,9,3,1;state,2
 wf,9,5,1;state,2
 wf,9,8,1;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,9,2,1
 occ,1,2,1,0,1,0,0
 closed,1,1,1,0,1,0,0
}
endproc






proc VIIXeandF
{rhf
 start,atden
 wf,8,1,0
 occ,1,1,1,0,1,0,0
}
endproc





proc Xp3
{rhf
 start,atden
 print,orbitals=2
 wf,5,8,3
 occ,1,1,1,0,1,0,0
 closed,1,0,0,0,0,0,0
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,1,1,1,0,1,0,0
 closed,1,0,0,0,0,0,0
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,5,8,3
 occ,1,1,1,0,1,0,0
 closed,1,0,0,0,0,0,0
}
endproc




proc XIIIs2
{rhf
 start,atden
 wf,2,1,0
 occ,1,0,0,0,0,0,0
 closed,1,0,0,0,0,0
}
endproc



