#!/bin/bash

HOME=`pwd`

cp aeinput/ae1.d yoon-modified/ip.d

cd yoon-modified

./a.out &> energy.output
grep 'TOTAL' energy.output | awk -F '-' {'printf("%.6f\n", -$2)'} > $HOME/energy.dat
for i in 2 3 4 5 6 7 8 9 10 11 12 13 14 
do

cp ../aeinput/ae$i.d ip.d

./a.out &> energy.output
grep 'TOTAL' energy.output | awk -F '-' {'printf("%.6f\n", -$2)'} >> $HOME/energy.dat
done
