#!/bin/bash
#COBALT -t 02:00:00
#COBALT -n 128
#COBALT -A PSFMat_2               
#COBALT -o myqwalk.o%j         
#COBALT -q default
#COBALT --attrs mcdram=cache:numa=quad


#aprun -n 8192 -N 64 qwalk-so Bi2.df

aprun -n 8192 -N 64 qwalk-so Bi2.opt

sed 's/OPTIMIZEBASIS//g' Bi2.opt.wfout > fixed_basis.wfout

aprun -n 8192 -N 64 qwalk-so Bi2.linear

aprun -n 8192 -N 64 qwalk-so Bi2.dmc


