#!/bin/bash -l
#SBATCH -J test_molpro
#SBATCH -q regular
#SBATCH -N 1
#!SBATCH -n 16
#SBATCH -C haswell
#SBATCH -t 00:30:00
#SBATCH -o test_molpro.o%j

module load molpro
molpro -n 8 dz.com
molpro -n 8 tz.com
molpro -n 8 qz.com
#molpro -n 8 5z.com
