#!/bin/bash -l
#SBATCH -J MWB1
#SBATCH -q debug
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -t 00:30:00
#SBATCH -o test_molpro.o%j

module load molpro
#molpro -n 24 dz.com
#molpro -n 24 tz.com
#molpro -n 24 qz.com
molpro -n 24 5z_1.com

