proc Id5s1
{rhf
 start,atden
 print,orbitals=2
 wf,42,1,6
 occ,9,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2,1
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,9,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 wf,42,1,6;state,1
 restrict,1,1,9.1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,42,1,6
 occ,9,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
}
endproc



proc Id5
{rhf
 start,atden
 print,orbitals=2
 wf,41,1,5
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,41,1,5
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
}
endproc




proc Id5p1
{rhf
 start,atden
 print,orbitals=2
 wf,42,2,6
 occ,8,4,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,8,4,4,3,4,2,2
 closed,6,3,3,1,3,1,1
 wf,42,2,6;state,1
 restrict,1,1,4.2
 wf,42,3,6;state,1
 restrict,1,1,4.3
 wf,42,5,6;state,1
 restrict,1,1,4.5
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,42,2,6
 occ,8,4,3,2,3,2,2
 closed,6,3,3,1,3,1,1
}
endproc




proc EAd5s2
{rhf
 start,atden
 print,orbitals=2
 wf,43,1,5
 occ,9,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,9,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,43,1,5
 occ,9,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,1,3,2
}
endproc




proc IId4s1
{rhf
 start,atden
 print,orbitals=2
 wf,41,1,5
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,1
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,9,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 wf,41,1,5;state,2
 restrict,1,1,9.1
 wf,41,4,5;state,1
 restrict,1,1,9.1
 wf,41,6,5;state,1
 restrict,1,1,9.1
 wf,41,7,5;state,1
 restrict,1,1,9.1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,41,1,5
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
}
endproc






proc IId4s2
{rhf
 start,atden
 print,orbitals=2
 wf,42,1,4
 occ,8,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,9,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 wf,42,1,4;state,2
 wf,42,4,4;state,1
 wf,42,6,4;state,1
 wf,42,7,4;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,42,1,4
 occ,8,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,1,3,2
}
endproc



proc IId3s2
{rhf
 start,atden
 print,orbitals=2
 wf,41,1,3
 occ,7,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,9,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 wf,41,1,3;state,1
 wf,41,4,3;state,3
 wf,41,6,3;state,3
 wf,41,7,3;state,3
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,41,1,3
 occ,7,3,3,2,3,2,2
 closed,7,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,1,3,2
}
endproc





proc IIId4
{rhf
 start,atden
 print,orbitals=2
 wf,40,1,4
 occ,7,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 wf,40,1,4;state,2
 wf,40,4,4;state,1
 wf,40,6,4;state,1
 wf,40,7,4;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,40,1,4
 occ,7,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
}
endproc




proc IVd3
{rhf
 start,atden
 print,orbitals=2
 wf,39,1,3
 occ,6,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 wf,39,1,3;state,1
 wf,39,4,3;state,3
 wf,39,6,3;state,3
 wf,39,7,3;state,3
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,39,1,3
 occ,6,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
}
endproc




proc Vd2
{rhf
 start,atden
 print,orbitals=2
 wf,38,1,2
 occ,8,3,3,1,3,1,1
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 wf,38,1,2;state,1
 wf,38,4,2;state,3
 wf,38,6,2;state,3
 wf,38,7,2;state,3
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,38,1,2
 occ,8,3,3,1,3,1,1
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3,2
}
endproc





proc VId1
{rhf
 start,atden
 print,orbitals=2
 wf,37,1,1
 occ,7,3,3,1,3,1,1
 closed,6,3,3,1,3,1,1
 sym,1,1,1,1,3,2,1,3
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,8,3,3,2,3,2,2
 closed,6,3,3,1,3,1,1
 wf,37,1,1;state,2
 wf,37,4,1;state,1
 wf,37,6,1;state,1
 wf,37,7,1;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,37,1,1
 occ,7,3,3,1,3,1,1
 closed,6,3,3,1,3,1,1
}
endproc





proc VIp1
{rhf
 start,atden
 print,orbitals=2
 wf,37,2,1
 occ,6,4,3,1,3,1,1
 closed,6,3,3,1,3,1,1
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,6,4,4,1,4,1,1
 closed,6,3,3,1,3,1,1
 wf,37,2,1;state,1
 restrict,1,1,4.2
 wf,37,3,1;state,1
 restrict,1,1,4.3
 wf,37,5,1;state,1
 restrict,1,1,4.5
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,37,2,1
 occ,6,4,3,1,3,1,1
 closed,6,3,3,1,3,1,1
}
endproc




proc VI5f1
{rhf
 start,atden
 print,orbitals=2
 wf,37,2,1
 occ,6,4,3,1,3,1,1
 closed,6,3,3,1,3,1,1
 sym,2,1,1,1,3,2
 sym,3,1,1,1,3,2
 sym,5,1,1,1,3,2
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,6,5,5,1,5,1,1,1
 closed,6,3,3,1,3,1,1
 wf,37,2,1;state,2
 wf,37,3,1;state,2
 wf,37,5,1;state,2
 wf,37,8,1;state,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,37,2,1
 occ,6,4,3,1,3,1,1
 closed,6,3,3,1,3,1,1
}
endproc






proc VIIXeandF
{rhf
 start,atden
 wf,36,1,0
 occ,6,3,3,1,3,1,1
}
endproc





proc Xp3
{rhf
 start,atden
 print,orbitals=2
 wf,33,8,3
 occ,6,3,3,1,3,1,1
 closed,6,2,2,1,2,1,1
 orbital,4202.2
}
pop
{multi
 start,4202.2
 occ,6,3,3,1,3,1,1
 closed,6,2,2,1,2,1,1
 natorb,ci,print
 orbital,5202.2
}
{rhf,nitord=1,maxit=0
 start,5202.2
 wf,33,8,3
 occ,6,3,3,1,3,1,1
 closed,6,2,2,1,2,1,1
}
endproc




proc XIIIs2
{rhf
 start,atden
 wf,30,1,0
 occ,6,2,2,1,2,1,1
}
endproc



