#!/bin/bash
HOME=`pwd`

declare -a states=("gs" "ex" "ea" "ip1" "ip2" "p1" "4p")
declare -a mult_num=(7 5 1 5 5 2 2)

num_states=${#states[@]}

for (( i=0; i<$num_states; i++))
do
	state=${states[$i]}
	num=${mult_num[$i]}

	for ((j=1; j<=$num; j++))
	do	
		cd $HOME/$state/state$j
		sbatch dmc.slurm
	done
done
