#!/bin/bash
HOME=`pwd`

declare -a states=("gs" "ex" "ea" "ip1" "ip2" "p1" "4p")
#declare -a mult_num=(7 5 1 5 5 2 2)

num_states=${#states[@]}

for (( i=0; i<$num_states; i++))
do
	state=${states[$i]}
	cd $HOME/../$state/opt
	sbatch opt-2.slurm
done
