#!/bin/bash -l
#SBATCH -J Ir_DMC
#SBATCH -q regular
#SBATCH -N 8
#SBATCH -C haswell
#SBATCH -t 00:20:00
#SBATCH -o so_qwalk.o%j

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ir.df

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ir.opt2
python add3bodyjs.py
srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ir.opt3

sed 's/OPTIMIZEBASIS//g' Ir.opt3.wfout > fixed_basis.wfout

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Ir.linear

sbatch jobdmc
