#!/bin/bash -l
#SBATCH -J Au2_DMC
#SBATCH -q regular
#SBATCH -N 8
#SBATCH -C haswell
#SBATCH -t 01:00:00
#SBATCH -o so_qwalk.o%j

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Au2.hf

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Au2.opt2
python add3bodyjs.py
srun -n 512 -c 1 --cpu_bind=threads qwalk-so Au2.opt3

sed 's/OPTIMIZEBASIS//g' Au2.opt3.wfout > fixed_basis.wfout

srun -n 512 -c 1 --cpu_bind=threads qwalk-so Au2.linear

sbatch jobdmc
